# Site settings
title: Christopher Troup
email: minichate@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A rarely updated blog 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://minichate.github.io" # the base hostname & protocol for your site
enforce_ssl: "minichate.github.io"
twitter_username: minichate
github_username:  minichate

# Build settings
markdown: kramdown
